# Generated by Django 4.2 on 2023-04-11 09:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0004_remove_post_user_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='posts_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
